# Generated by Django 2.0rc1 on 2017-12-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('album', models.CharField(max_length=200)),
                ('album_image', models.CharField(max_length=200)),
                ('youtube_id', models.CharField(max_length=200)),
                ('tab', models.TextField()),
                ('lyrics', models.TextField()),
            ],
        ),
    ]
